// AUTOMATICALLY GENERATED. DO NOT EDIT.

pub use self::SyscallNo::*;
use core::fmt;
#[cfg(feature = "serde_repr")]
use serde_repr::{Deserialize_repr, Serialize_repr};
#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
#[derive(PartialEq, Eq, Clone, Copy)]
#[cfg_attr(feature = "serde_repr", derive(Serialize_repr, Deserialize_repr))]
#[repr(i32)]
pub enum SyscallNo {
    SYS_read = 0,
    SYS_write = 1,
    SYS_open = 2,
    SYS_close = 3,
    SYS_stat = 4,
    SYS_fstat = 5,
    SYS_lstat = 6,
    SYS_poll = 7,
    SYS_lseek = 8,
    SYS_mmap = 9,
    SYS_mprotect = 10,
    SYS_munmap = 11,
    SYS_brk = 12,
    SYS_rt_sigaction = 13,
    SYS_rt_sigprocmask = 14,
    SYS_rt_sigreturn = 15,
    SYS_ioctl = 16,
    SYS_pread64 = 17,
    SYS_pwrite64 = 18,
    SYS_readv = 19,
    SYS_writev = 20,
    SYS_access = 21,
    SYS_pipe = 22,
    SYS_select = 23,
    SYS_sched_yield = 24,
    SYS_mremap = 25,
    SYS_msync = 26,
    SYS_mincore = 27,
    SYS_madvise = 28,
    SYS_shmget = 29,
    SYS_shmat = 30,
    SYS_shmctl = 31,
    SYS_dup = 32,
    SYS_dup2 = 33,
    SYS_pause = 34,
    SYS_nanosleep = 35,
    SYS_getitimer = 36,
    SYS_alarm = 37,
    SYS_setitimer = 38,
    SYS_getpid = 39,
    SYS_sendfile = 40,
    SYS_socket = 41,
    SYS_connect = 42,
    SYS_accept = 43,
    SYS_sendto = 44,
    SYS_recvfrom = 45,
    SYS_sendmsg = 46,
    SYS_recvmsg = 47,
    SYS_shutdown = 48,
    SYS_bind = 49,
    SYS_listen = 50,
    SYS_getsockname = 51,
    SYS_getpeername = 52,
    SYS_socketpair = 53,
    SYS_setsockopt = 54,
    SYS_getsockopt = 55,
    SYS_clone = 56,
    SYS_fork = 57,
    SYS_vfork = 58,
    SYS_execve = 59,
    SYS_exit = 60,
    SYS_wait4 = 61,
    SYS_kill = 62,
    SYS_uname = 63,
    SYS_semget = 64,
    SYS_semop = 65,
    SYS_semctl = 66,
    SYS_shmdt = 67,
    SYS_msgget = 68,
    SYS_msgsnd = 69,
    SYS_msgrcv = 70,
    SYS_msgctl = 71,
    SYS_fcntl = 72,
    SYS_flock = 73,
    SYS_fsync = 74,
    SYS_fdatasync = 75,
    SYS_truncate = 76,
    SYS_ftruncate = 77,
    SYS_getdents = 78,
    SYS_getcwd = 79,
    SYS_chdir = 80,
    SYS_fchdir = 81,
    SYS_rename = 82,
    SYS_mkdir = 83,
    SYS_rmdir = 84,
    SYS_creat = 85,
    SYS_link = 86,
    SYS_unlink = 87,
    SYS_symlink = 88,
    SYS_readlink = 89,
    SYS_chmod = 90,
    SYS_fchmod = 91,
    SYS_chown = 92,
    SYS_fchown = 93,
    SYS_lchown = 94,
    SYS_umask = 95,
    SYS_gettimeofday = 96,
    SYS_getrlimit = 97,
    SYS_getrusage = 98,
    SYS_sysinfo = 99,
    SYS_times = 100,
    SYS_ptrace = 101,
    SYS_getuid = 102,
    SYS_syslog = 103,
    SYS_getgid = 104,
    SYS_setuid = 105,
    SYS_setgid = 106,
    SYS_geteuid = 107,
    SYS_getegid = 108,
    SYS_setpgid = 109,
    SYS_getppid = 110,
    SYS_getpgrp = 111,
    SYS_setsid = 112,
    SYS_setreuid = 113,
    SYS_setregid = 114,
    SYS_getgroups = 115,
    SYS_setgroups = 116,
    SYS_setresuid = 117,
    SYS_getresuid = 118,
    SYS_setresgid = 119,
    SYS_getresgid = 120,
    SYS_getpgid = 121,
    SYS_setfsuid = 122,
    SYS_setfsgid = 123,
    SYS_getsid = 124,
    SYS_capget = 125,
    SYS_capset = 126,
    SYS_rt_sigpending = 127,
    SYS_rt_sigtimedwait = 128,
    SYS_rt_sigqueueinfo = 129,
    SYS_rt_sigsuspend = 130,
    SYS_sigaltstack = 131,
    SYS_utime = 132,
    SYS_mknod = 133,
    SYS_uselib = 134,
    SYS_personality = 135,
    SYS_ustat = 136,
    SYS_statfs = 137,
    SYS_fstatfs = 138,
    SYS_sysfs = 139,
    SYS_getpriority = 140,
    SYS_setpriority = 141,
    SYS_sched_setparam = 142,
    SYS_sched_getparam = 143,
    SYS_sched_setscheduler = 144,
    SYS_sched_getscheduler = 145,
    SYS_sched_get_priority_max = 146,
    SYS_sched_get_priority_min = 147,
    SYS_sched_rr_get_interval = 148,
    SYS_mlock = 149,
    SYS_munlock = 150,
    SYS_mlockall = 151,
    SYS_munlockall = 152,
    SYS_vhangup = 153,
    SYS_modify_ldt = 154,
    SYS_pivot_root = 155,
    SYS__sysctl = 156,
    SYS_prctl = 157,
    SYS_arch_prctl = 158,
    SYS_adjtimex = 159,
    SYS_setrlimit = 160,
    SYS_chroot = 161,
    SYS_sync = 162,
    SYS_acct = 163,
    SYS_settimeofday = 164,
    SYS_mount = 165,
    SYS_umount2 = 166,
    SYS_swapon = 167,
    SYS_swapoff = 168,
    SYS_reboot = 169,
    SYS_sethostname = 170,
    SYS_setdomainname = 171,
    SYS_iopl = 172,
    SYS_ioperm = 173,
    SYS_create_module = 174,
    SYS_init_module = 175,
    SYS_delete_module = 176,
    SYS_get_kernel_syms = 177,
    SYS_query_module = 178,
    SYS_quotactl = 179,
    SYS_nfsservctl = 180,
    SYS_getpmsg = 181,
    SYS_putpmsg = 182,
    SYS_afs_syscall = 183,
    SYS_tuxcall = 184,
    SYS_security = 185,
    SYS_gettid = 186,
    SYS_readahead = 187,
    SYS_setxattr = 188,
    SYS_lsetxattr = 189,
    SYS_fsetxattr = 190,
    SYS_getxattr = 191,
    SYS_lgetxattr = 192,
    SYS_fgetxattr = 193,
    SYS_listxattr = 194,
    SYS_llistxattr = 195,
    SYS_flistxattr = 196,
    SYS_removexattr = 197,
    SYS_lremovexattr = 198,
    SYS_fremovexattr = 199,
    SYS_tkill = 200,
    SYS_time = 201,
    SYS_futex = 202,
    SYS_sched_setaffinity = 203,
    SYS_sched_getaffinity = 204,
    SYS_set_thread_area = 205,
    SYS_io_setup = 206,
    SYS_io_destroy = 207,
    SYS_io_getevents = 208,
    SYS_io_submit = 209,
    SYS_io_cancel = 210,
    SYS_get_thread_area = 211,
    SYS_lookup_dcookie = 212,
    SYS_epoll_create = 213,
    SYS_epoll_ctl_old = 214,
    SYS_epoll_wait_old = 215,
    SYS_remap_file_pages = 216,
    SYS_getdents64 = 217,
    SYS_set_tid_address = 218,
    SYS_restart_syscall = 219,
    SYS_semtimedop = 220,
    SYS_fadvise64 = 221,
    SYS_timer_create = 222,
    SYS_timer_settime = 223,
    SYS_timer_gettime = 224,
    SYS_timer_getoverrun = 225,
    SYS_timer_delete = 226,
    SYS_clock_settime = 227,
    SYS_clock_gettime = 228,
    SYS_clock_getres = 229,
    SYS_clock_nanosleep = 230,
    SYS_exit_group = 231,
    SYS_epoll_wait = 232,
    SYS_epoll_ctl = 233,
    SYS_tgkill = 234,
    SYS_utimes = 235,
    SYS_vserver = 236,
    SYS_mbind = 237,
    SYS_set_mempolicy = 238,
    SYS_get_mempolicy = 239,
    SYS_mq_open = 240,
    SYS_mq_unlink = 241,
    SYS_mq_timedsend = 242,
    SYS_mq_timedreceive = 243,
    SYS_mq_notify = 244,
    SYS_mq_getsetattr = 245,
    SYS_kexec_load = 246,
    SYS_waitid = 247,
    SYS_add_key = 248,
    SYS_request_key = 249,
    SYS_keyctl = 250,
    SYS_ioprio_set = 251,
    SYS_ioprio_get = 252,
    SYS_inotify_init = 253,
    SYS_inotify_add_watch = 254,
    SYS_inotify_rm_watch = 255,
    SYS_migrate_pages = 256,
    SYS_openat = 257,
    SYS_mkdirat = 258,
    SYS_mknodat = 259,
    SYS_fchownat = 260,
    SYS_futimesat = 261,
    SYS_newfstatat = 262,
    SYS_unlinkat = 263,
    SYS_renameat = 264,
    SYS_linkat = 265,
    SYS_symlinkat = 266,
    SYS_readlinkat = 267,
    SYS_fchmodat = 268,
    SYS_faccessat = 269,
    SYS_pselect6 = 270,
    SYS_ppoll = 271,
    SYS_unshare = 272,
    SYS_set_robust_list = 273,
    SYS_get_robust_list = 274,
    SYS_splice = 275,
    SYS_tee = 276,
    SYS_sync_file_range = 277,
    SYS_vmsplice = 278,
    SYS_move_pages = 279,
    SYS_utimensat = 280,
    SYS_epoll_pwait = 281,
    SYS_signalfd = 282,
    SYS_timerfd_create = 283,
    SYS_eventfd = 284,
    SYS_fallocate = 285,
    SYS_timerfd_settime = 286,
    SYS_timerfd_gettime = 287,
    SYS_accept4 = 288,
    SYS_signalfd4 = 289,
    SYS_eventfd2 = 290,
    SYS_epoll_create1 = 291,
    SYS_dup3 = 292,
    SYS_pipe2 = 293,
    SYS_inotify_init1 = 294,
    SYS_preadv = 295,
    SYS_pwritev = 296,
    SYS_rt_tgsigqueueinfo = 297,
    SYS_perf_event_open = 298,
    SYS_recvmmsg = 299,
    SYS_fanotify_init = 300,
    SYS_fanotify_mark = 301,
    SYS_prlimit64 = 302,
    SYS_name_to_handle_at = 303,
    SYS_open_by_handle_at = 304,
    SYS_clock_adjtime = 305,
    SYS_syncfs = 306,
    SYS_sendmmsg = 307,
    SYS_setns = 308,
    SYS_getcpu = 309,
    SYS_process_vm_readv = 310,
    SYS_process_vm_writev = 311,
    SYS_kcmp = 312,
    SYS_finit_module = 313,
    SYS_sched_setattr = 314,
    SYS_sched_getattr = 315,
    SYS_renameat2 = 316,
    SYS_seccomp = 317,
    SYS_getrandom = 318,
    SYS_memfd_create = 319,
    SYS_kexec_file_load = 320,
    SYS_bpf = 321,
    SYS_execveat = 322,
    SYS_userfaultfd = 323,
    SYS_membarrier = 324,
    SYS_mlock2 = 325,
    SYS_copy_file_range = 326,
    SYS_preadv2 = 327,
    SYS_pwritev2 = 328,
    SYS_pkey_mprotect = 329,
    SYS_pkey_alloc = 330,
    SYS_pkey_free = 331,
    SYS_statx = 332,
    SYS_io_pgetevents = 333,
    SYS_rseq = 334,
    SYS_pidfd_send_signal = 424,
    SYS_io_uring_setup = 425,
    SYS_io_uring_enter = 426,
    SYS_io_uring_register = 427,
    SYS_open_tree = 428,
    SYS_move_mount = 429,
    SYS_fsopen = 430,
    SYS_fsconfig = 431,
    SYS_fsmount = 432,
    SYS_fspick = 433,
}
static SYSCALL_NAMES: [&str; 345] = [
    "read",
    "write",
    "open",
    "close",
    "stat",
    "fstat",
    "lstat",
    "poll",
    "lseek",
    "mmap",
    "mprotect",
    "munmap",
    "brk",
    "rt_sigaction",
    "rt_sigprocmask",
    "rt_sigreturn",
    "ioctl",
    "pread64",
    "pwrite64",
    "readv",
    "writev",
    "access",
    "pipe",
    "select",
    "sched_yield",
    "mremap",
    "msync",
    "mincore",
    "madvise",
    "shmget",
    "shmat",
    "shmctl",
    "dup",
    "dup2",
    "pause",
    "nanosleep",
    "getitimer",
    "alarm",
    "setitimer",
    "getpid",
    "sendfile",
    "socket",
    "connect",
    "accept",
    "sendto",
    "recvfrom",
    "sendmsg",
    "recvmsg",
    "shutdown",
    "bind",
    "listen",
    "getsockname",
    "getpeername",
    "socketpair",
    "setsockopt",
    "getsockopt",
    "clone",
    "fork",
    "vfork",
    "execve",
    "exit",
    "wait4",
    "kill",
    "uname",
    "semget",
    "semop",
    "semctl",
    "shmdt",
    "msgget",
    "msgsnd",
    "msgrcv",
    "msgctl",
    "fcntl",
    "flock",
    "fsync",
    "fdatasync",
    "truncate",
    "ftruncate",
    "getdents",
    "getcwd",
    "chdir",
    "fchdir",
    "rename",
    "mkdir",
    "rmdir",
    "creat",
    "link",
    "unlink",
    "symlink",
    "readlink",
    "chmod",
    "fchmod",
    "chown",
    "fchown",
    "lchown",
    "umask",
    "gettimeofday",
    "getrlimit",
    "getrusage",
    "sysinfo",
    "times",
    "ptrace",
    "getuid",
    "syslog",
    "getgid",
    "setuid",
    "setgid",
    "geteuid",
    "getegid",
    "setpgid",
    "getppid",
    "getpgrp",
    "setsid",
    "setreuid",
    "setregid",
    "getgroups",
    "setgroups",
    "setresuid",
    "getresuid",
    "setresgid",
    "getresgid",
    "getpgid",
    "setfsuid",
    "setfsgid",
    "getsid",
    "capget",
    "capset",
    "rt_sigpending",
    "rt_sigtimedwait",
    "rt_sigqueueinfo",
    "rt_sigsuspend",
    "sigaltstack",
    "utime",
    "mknod",
    "uselib",
    "personality",
    "ustat",
    "statfs",
    "fstatfs",
    "sysfs",
    "getpriority",
    "setpriority",
    "sched_setparam",
    "sched_getparam",
    "sched_setscheduler",
    "sched_getscheduler",
    "sched_get_priority_max",
    "sched_get_priority_min",
    "sched_rr_get_interval",
    "mlock",
    "munlock",
    "mlockall",
    "munlockall",
    "vhangup",
    "modify_ldt",
    "pivot_root",
    "_sysctl",
    "prctl",
    "arch_prctl",
    "adjtimex",
    "setrlimit",
    "chroot",
    "sync",
    "acct",
    "settimeofday",
    "mount",
    "umount2",
    "swapon",
    "swapoff",
    "reboot",
    "sethostname",
    "setdomainname",
    "iopl",
    "ioperm",
    "create_module",
    "init_module",
    "delete_module",
    "get_kernel_syms",
    "query_module",
    "quotactl",
    "nfsservctl",
    "getpmsg",
    "putpmsg",
    "afs_syscall",
    "tuxcall",
    "security",
    "gettid",
    "readahead",
    "setxattr",
    "lsetxattr",
    "fsetxattr",
    "getxattr",
    "lgetxattr",
    "fgetxattr",
    "listxattr",
    "llistxattr",
    "flistxattr",
    "removexattr",
    "lremovexattr",
    "fremovexattr",
    "tkill",
    "time",
    "futex",
    "sched_setaffinity",
    "sched_getaffinity",
    "set_thread_area",
    "io_setup",
    "io_destroy",
    "io_getevents",
    "io_submit",
    "io_cancel",
    "get_thread_area",
    "lookup_dcookie",
    "epoll_create",
    "epoll_ctl_old",
    "epoll_wait_old",
    "remap_file_pages",
    "getdents64",
    "set_tid_address",
    "restart_syscall",
    "semtimedop",
    "fadvise64",
    "timer_create",
    "timer_settime",
    "timer_gettime",
    "timer_getoverrun",
    "timer_delete",
    "clock_settime",
    "clock_gettime",
    "clock_getres",
    "clock_nanosleep",
    "exit_group",
    "epoll_wait",
    "epoll_ctl",
    "tgkill",
    "utimes",
    "vserver",
    "mbind",
    "set_mempolicy",
    "get_mempolicy",
    "mq_open",
    "mq_unlink",
    "mq_timedsend",
    "mq_timedreceive",
    "mq_notify",
    "mq_getsetattr",
    "kexec_load",
    "waitid",
    "add_key",
    "request_key",
    "keyctl",
    "ioprio_set",
    "ioprio_get",
    "inotify_init",
    "inotify_add_watch",
    "inotify_rm_watch",
    "migrate_pages",
    "openat",
    "mkdirat",
    "mknodat",
    "fchownat",
    "futimesat",
    "newfstatat",
    "unlinkat",
    "renameat",
    "linkat",
    "symlinkat",
    "readlinkat",
    "fchmodat",
    "faccessat",
    "pselect6",
    "ppoll",
    "unshare",
    "set_robust_list",
    "get_robust_list",
    "splice",
    "tee",
    "sync_file_range",
    "vmsplice",
    "move_pages",
    "utimensat",
    "epoll_pwait",
    "signalfd",
    "timerfd_create",
    "eventfd",
    "fallocate",
    "timerfd_settime",
    "timerfd_gettime",
    "accept4",
    "signalfd4",
    "eventfd2",
    "epoll_create1",
    "dup3",
    "pipe2",
    "inotify_init1",
    "preadv",
    "pwritev",
    "rt_tgsigqueueinfo",
    "perf_event_open",
    "recvmmsg",
    "fanotify_init",
    "fanotify_mark",
    "prlimit64",
    "name_to_handle_at",
    "open_by_handle_at",
    "clock_adjtime",
    "syncfs",
    "sendmmsg",
    "setns",
    "getcpu",
    "process_vm_readv",
    "process_vm_writev",
    "kcmp",
    "finit_module",
    "sched_setattr",
    "sched_getattr",
    "renameat2",
    "seccomp",
    "getrandom",
    "memfd_create",
    "kexec_file_load",
    "bpf",
    "execveat",
    "userfaultfd",
    "membarrier",
    "mlock2",
    "copy_file_range",
    "preadv2",
    "pwritev2",
    "pkey_mprotect",
    "pkey_alloc",
    "pkey_free",
    "statx",
    "io_pgetevents",
    "rseq",
    "pidfd_send_signal",
    "io_uring_setup",
    "io_uring_enter",
    "io_uring_register",
    "open_tree",
    "move_mount",
    "fsopen",
    "fsconfig",
    "fsmount",
    "fspick",
];

impl SyscallNo {
    #[inline]
    fn name(&self) -> &'static str {
        SYSCALL_NAMES[*self as usize]
    }
}

impl fmt::Debug for SyscallNo {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str(self.name())
    }
}

static SYSCALL_IDS: [SyscallNo; 345] = [
    SYS_read,
    SYS_write,
    SYS_open,
    SYS_close,
    SYS_stat,
    SYS_fstat,
    SYS_lstat,
    SYS_poll,
    SYS_lseek,
    SYS_mmap,
    SYS_mprotect,
    SYS_munmap,
    SYS_brk,
    SYS_rt_sigaction,
    SYS_rt_sigprocmask,
    SYS_rt_sigreturn,
    SYS_ioctl,
    SYS_pread64,
    SYS_pwrite64,
    SYS_readv,
    SYS_writev,
    SYS_access,
    SYS_pipe,
    SYS_select,
    SYS_sched_yield,
    SYS_mremap,
    SYS_msync,
    SYS_mincore,
    SYS_madvise,
    SYS_shmget,
    SYS_shmat,
    SYS_shmctl,
    SYS_dup,
    SYS_dup2,
    SYS_pause,
    SYS_nanosleep,
    SYS_getitimer,
    SYS_alarm,
    SYS_setitimer,
    SYS_getpid,
    SYS_sendfile,
    SYS_socket,
    SYS_connect,
    SYS_accept,
    SYS_sendto,
    SYS_recvfrom,
    SYS_sendmsg,
    SYS_recvmsg,
    SYS_shutdown,
    SYS_bind,
    SYS_listen,
    SYS_getsockname,
    SYS_getpeername,
    SYS_socketpair,
    SYS_setsockopt,
    SYS_getsockopt,
    SYS_clone,
    SYS_fork,
    SYS_vfork,
    SYS_execve,
    SYS_exit,
    SYS_wait4,
    SYS_kill,
    SYS_uname,
    SYS_semget,
    SYS_semop,
    SYS_semctl,
    SYS_shmdt,
    SYS_msgget,
    SYS_msgsnd,
    SYS_msgrcv,
    SYS_msgctl,
    SYS_fcntl,
    SYS_flock,
    SYS_fsync,
    SYS_fdatasync,
    SYS_truncate,
    SYS_ftruncate,
    SYS_getdents,
    SYS_getcwd,
    SYS_chdir,
    SYS_fchdir,
    SYS_rename,
    SYS_mkdir,
    SYS_rmdir,
    SYS_creat,
    SYS_link,
    SYS_unlink,
    SYS_symlink,
    SYS_readlink,
    SYS_chmod,
    SYS_fchmod,
    SYS_chown,
    SYS_fchown,
    SYS_lchown,
    SYS_umask,
    SYS_gettimeofday,
    SYS_getrlimit,
    SYS_getrusage,
    SYS_sysinfo,
    SYS_times,
    SYS_ptrace,
    SYS_getuid,
    SYS_syslog,
    SYS_getgid,
    SYS_setuid,
    SYS_setgid,
    SYS_geteuid,
    SYS_getegid,
    SYS_setpgid,
    SYS_getppid,
    SYS_getpgrp,
    SYS_setsid,
    SYS_setreuid,
    SYS_setregid,
    SYS_getgroups,
    SYS_setgroups,
    SYS_setresuid,
    SYS_getresuid,
    SYS_setresgid,
    SYS_getresgid,
    SYS_getpgid,
    SYS_setfsuid,
    SYS_setfsgid,
    SYS_getsid,
    SYS_capget,
    SYS_capset,
    SYS_rt_sigpending,
    SYS_rt_sigtimedwait,
    SYS_rt_sigqueueinfo,
    SYS_rt_sigsuspend,
    SYS_sigaltstack,
    SYS_utime,
    SYS_mknod,
    SYS_uselib,
    SYS_personality,
    SYS_ustat,
    SYS_statfs,
    SYS_fstatfs,
    SYS_sysfs,
    SYS_getpriority,
    SYS_setpriority,
    SYS_sched_setparam,
    SYS_sched_getparam,
    SYS_sched_setscheduler,
    SYS_sched_getscheduler,
    SYS_sched_get_priority_max,
    SYS_sched_get_priority_min,
    SYS_sched_rr_get_interval,
    SYS_mlock,
    SYS_munlock,
    SYS_mlockall,
    SYS_munlockall,
    SYS_vhangup,
    SYS_modify_ldt,
    SYS_pivot_root,
    SYS__sysctl,
    SYS_prctl,
    SYS_arch_prctl,
    SYS_adjtimex,
    SYS_setrlimit,
    SYS_chroot,
    SYS_sync,
    SYS_acct,
    SYS_settimeofday,
    SYS_mount,
    SYS_umount2,
    SYS_swapon,
    SYS_swapoff,
    SYS_reboot,
    SYS_sethostname,
    SYS_setdomainname,
    SYS_iopl,
    SYS_ioperm,
    SYS_create_module,
    SYS_init_module,
    SYS_delete_module,
    SYS_get_kernel_syms,
    SYS_query_module,
    SYS_quotactl,
    SYS_nfsservctl,
    SYS_getpmsg,
    SYS_putpmsg,
    SYS_afs_syscall,
    SYS_tuxcall,
    SYS_security,
    SYS_gettid,
    SYS_readahead,
    SYS_setxattr,
    SYS_lsetxattr,
    SYS_fsetxattr,
    SYS_getxattr,
    SYS_lgetxattr,
    SYS_fgetxattr,
    SYS_listxattr,
    SYS_llistxattr,
    SYS_flistxattr,
    SYS_removexattr,
    SYS_lremovexattr,
    SYS_fremovexattr,
    SYS_tkill,
    SYS_time,
    SYS_futex,
    SYS_sched_setaffinity,
    SYS_sched_getaffinity,
    SYS_set_thread_area,
    SYS_io_setup,
    SYS_io_destroy,
    SYS_io_getevents,
    SYS_io_submit,
    SYS_io_cancel,
    SYS_get_thread_area,
    SYS_lookup_dcookie,
    SYS_epoll_create,
    SYS_epoll_ctl_old,
    SYS_epoll_wait_old,
    SYS_remap_file_pages,
    SYS_getdents64,
    SYS_set_tid_address,
    SYS_restart_syscall,
    SYS_semtimedop,
    SYS_fadvise64,
    SYS_timer_create,
    SYS_timer_settime,
    SYS_timer_gettime,
    SYS_timer_getoverrun,
    SYS_timer_delete,
    SYS_clock_settime,
    SYS_clock_gettime,
    SYS_clock_getres,
    SYS_clock_nanosleep,
    SYS_exit_group,
    SYS_epoll_wait,
    SYS_epoll_ctl,
    SYS_tgkill,
    SYS_utimes,
    SYS_vserver,
    SYS_mbind,
    SYS_set_mempolicy,
    SYS_get_mempolicy,
    SYS_mq_open,
    SYS_mq_unlink,
    SYS_mq_timedsend,
    SYS_mq_timedreceive,
    SYS_mq_notify,
    SYS_mq_getsetattr,
    SYS_kexec_load,
    SYS_waitid,
    SYS_add_key,
    SYS_request_key,
    SYS_keyctl,
    SYS_ioprio_set,
    SYS_ioprio_get,
    SYS_inotify_init,
    SYS_inotify_add_watch,
    SYS_inotify_rm_watch,
    SYS_migrate_pages,
    SYS_openat,
    SYS_mkdirat,
    SYS_mknodat,
    SYS_fchownat,
    SYS_futimesat,
    SYS_newfstatat,
    SYS_unlinkat,
    SYS_renameat,
    SYS_linkat,
    SYS_symlinkat,
    SYS_readlinkat,
    SYS_fchmodat,
    SYS_faccessat,
    SYS_pselect6,
    SYS_ppoll,
    SYS_unshare,
    SYS_set_robust_list,
    SYS_get_robust_list,
    SYS_splice,
    SYS_tee,
    SYS_sync_file_range,
    SYS_vmsplice,
    SYS_move_pages,
    SYS_utimensat,
    SYS_epoll_pwait,
    SYS_signalfd,
    SYS_timerfd_create,
    SYS_eventfd,
    SYS_fallocate,
    SYS_timerfd_settime,
    SYS_timerfd_gettime,
    SYS_accept4,
    SYS_signalfd4,
    SYS_eventfd2,
    SYS_epoll_create1,
    SYS_dup3,
    SYS_pipe2,
    SYS_inotify_init1,
    SYS_preadv,
    SYS_pwritev,
    SYS_rt_tgsigqueueinfo,
    SYS_perf_event_open,
    SYS_recvmmsg,
    SYS_fanotify_init,
    SYS_fanotify_mark,
    SYS_prlimit64,
    SYS_name_to_handle_at,
    SYS_open_by_handle_at,
    SYS_clock_adjtime,
    SYS_syncfs,
    SYS_sendmmsg,
    SYS_setns,
    SYS_getcpu,
    SYS_process_vm_readv,
    SYS_process_vm_writev,
    SYS_kcmp,
    SYS_finit_module,
    SYS_sched_setattr,
    SYS_sched_getattr,
    SYS_renameat2,
    SYS_seccomp,
    SYS_getrandom,
    SYS_memfd_create,
    SYS_kexec_file_load,
    SYS_bpf,
    SYS_execveat,
    SYS_userfaultfd,
    SYS_membarrier,
    SYS_mlock2,
    SYS_copy_file_range,
    SYS_preadv2,
    SYS_pwritev2,
    SYS_pkey_mprotect,
    SYS_pkey_alloc,
    SYS_pkey_free,
    SYS_statx,
    SYS_io_pgetevents,
    SYS_rseq,
    SYS_pidfd_send_signal,
    SYS_io_uring_setup,
    SYS_io_uring_enter,
    SYS_io_uring_register,
    SYS_open_tree,
    SYS_move_mount,
    SYS_fsopen,
    SYS_fsconfig,
    SYS_fsmount,
    SYS_fspick,
];
impl From<i32> for SyscallNo {
    fn from(item: i32) -> Self {
        if item as usize > SYSCALL_IDS.len() {
            panic!("invalid syscall: {}", item)
        } else {
            SYSCALL_IDS[item as usize]
        }
    }
}
